sonar.projectKey=NestJS-DevOps
sonar.projectName=NestJS DevOps
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.tests=src

sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.typescript.tsconfigPaths=tsconfig.sonar.json
sonar.coverage.exclusions=src/main.ts,**/*.module.ts